### ISSUE TITLE
Global indention in documents.

### ISSUE THREAD

**Issue by fros1y** [commonform/commonform-samples#1]
Really interesting project! Quick question:  Is there a reason why commonform documents are globally indented one level? Not doing so actually seems to cause a hard crash in the parsing ("Error: Parse error on line 1: Unexpected 'BACKSLASH'"), so it's a very strong default.  Not sure I understand why, or whether that's just a bug.  (All the samples seem to follow this pattern, so I assume it's not a bug.)

Best,

**Comment by mengwong** [comment]
at the risk of sounding like a KKK member, without white space, there is no hierarchy and all would be chaos.

but, good point: why does everything have to start at 1 level of indentation rather than 0?

**Comment by kemitchell** [comment]
@fros1y, I'm sorry I missed this issue when you posted it. For a while there, I didn't receive e-mail notifications from GitHub. I'm still running into issues I wish I'd seen at the time.

You're right that this is valid:

```commonform
    \Heading\ Some text.
```

And that this is not:

```commonform
\Heading\ Some text.
```

Perhaps you've already noticed the common pattern for contracts:

```commonform
This is a something-of-other agreement between [A] and [B]. They agree:

    \Heading\  Some text. Here comes a list:
        \\  first
        \\  second
        \\  third

    \Another Heading\  Some more text.
```

I suppose we could make a special case for child forms at the top level, to save some indentation:

```commonform
This is a something-of-other agreement between [A] and [B]. They agree:

\Heading\  Some text. Here comes a list:
    \\  first
    \\  second
    \\  third

\Another Heading\  Some more text.
```

But that would make the rules for the "top level" slightly inconsistent with the rules for indentation in child forms.

At a higher level, Common Form's data schema sees all pieces of all forms the same. Each piece can contain text and other pieces. Like a Russian nesting doll, some levels are bigger than others, but all levels are shaped the same. The consistency of the markup rules reflects the consistent data shape of Common Form objects.

**Comment by kemitchell** [comment]
@mengwong: When in doubt, I try not to mention hate groups, even when I get a chance to chortle at their expense. It can take folks by surprise in a technical issue like this, and not always in a good way. Drop me an e-mail if you'd like to discuss.
